import "./globals.css";
import { Toaster } from "react-hot-toast";
import Layout from "../components/Layout"; // Adjust the path as necessary
import { StateContext } from "../context/StateContext";
export const metadata = {
  title: "Abhijeet's App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <StateContext>
          <Layout>
            <Toaster />
            {children}
          </Layout>
        </StateContext>
      </body>
    </html>
  );
}
