// import "./globals.css";
// import { Toaster } from "react-hot-toast";
// import Layout from "../components/Layout"; // Adjust the path as necessary
// import { StateContext } from "../context/StateContext";
// export const metadata = {
//   title: "Abhijeet's App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body suppressHydrationWarning={true}>
//         <StateContext>
//           <Layout>
//             <Toaster />
//             {children}
//           </Layout>
//         </StateContext>
//       </body>
//     </html>
//   );
// }

import "./globals.css";
import { Toaster } from "react-hot-toast";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import { StateContext } from "../context/StateContext";

export const metadata = {
  title: "Abhijeet's App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <StateContext>
          <div className="layout-wrapper">
            <header>
              <Navbar />
            </header>
            <main className="main-container">
              {children}
              <Toaster />
            </main>
            <footer>
              <Footer />
            </footer>
          </div>
        </StateContext>
      </body>
    </html>
  );
}
